### ISSUE TITLE
Mockup: Layout

### ISSUE THREAD

**Issue by Spawbreaker** [IntersysConsulting/mdc_team_b_front#1]
- [x] Design
- [x] Approval

**Comment by Spawbreaker** [comment]
Here's my first version of the mockup, you can also visualize it in https://www.figma.com/file/fFnQQH3qVT6CczKfhRmsNy/Layout-Mockup?node-id=0%3A1  

![Layout Mockup](https://user-images.githubusercontent.com/37517471/62790663-2e38a800-ba91-11e9-81bc-99a68c836333.png)

We are awaiting confirmation on collaboration accounts to join the team in figma, so we can start copying the Layout file into other mockups. 

**Does anyone have feedback on this layout?**

**Comment by pablorich** [comment]
En cuanto al diseño creo que hay que considerar un poco de padding en los titulos del menu y un icono diferente para la opcion de abrir el menu en la segunda vista

**Comment by Spawbreaker** [comment]
- Added padding to menu and title labels.
- Added a label to acknowledge if user is logged into the website.
- Changed the Small Desktop's menu icon when not collapsed to a tentative design, but it's still a placeholder. Final design should be discussed with product owner. 
- Fixed missing Option labels on Desktop's last category. 
- Added comments on Small Desktop's menu and the User label on all figures. 
![Layout Mockup (2)](https://user-images.githubusercontent.com/37517471/62800000-deb1a680-baa7-11e9-8924-fcb30f0d8675.png)

You may still preview the mockup in-app in [the same link.](https://www.figma.com/file/fFnQQH3qVT6CczKfhRmsNy/Layout-Mockup?node-id=0%3A1)

Does anyone have feedback on this layout? (You may react this with a thumbs up or thumbs down,
or comment or use slack to give direct feedback)

**Comment by Spawbreaker** [comment]
I'll close this one up in about an hour if nobody has any changes they want done to the layout.

After this one is done we can start working on the rest of the mockups using it as a template.
