### ISSUE TITLE
Mockup: Cart

### ISSUE THREAD

**Issue by Spawbreaker** [IntersysConsulting/mdc_team_b_front#12]
- [x] Design
- [ ] Approval

**Comment by alf-null** [comment]
Here's the first draft of the Mockup, let me know if you think that I should make any changes 
![Layout Mockup](https://user-images.githubusercontent.com/53229085/62903162-6fe28080-bd27-11e9-8572-7506c48f43e4.png)

**Comment by Spawbreaker** [comment]
Hey Alfredo! Looking great!
- I would consider adding (Or at least including a comment about) the possibility for an user to add or remove multiples of an item. You could base it off on Amazon's cart, where to delete an item you can select "0" items of a kind. 
- The button "Proceed to pay" should say "Proceed to checkout". 
- Maybe consider an empty cart view? Up to you. 
- Would be wise to add a comment on the admin section of the menu's visibility to non admin users, so that it isn't picked at by our client.

**Comment by pablorich** [comment]
Also the quantity of the product is pretty important, I would add it in the smaller views

**Comment by alf-null** [comment]
I think it's all fixed but your feedback it's very important, let me know if you see anything else.
![Layout Mockup (1)](https://user-images.githubusercontent.com/53229085/62974142-2bb1b780-bddd-11e9-9131-54f734a62fd1.png)

**Comment by pablorich** [comment]
Maybe we can delete the search item button in the menu since we have a searchbar in the main view.
Also we need a log out button.

**Comment by alf-null** [comment]
I just fixed the search button but regarding the log out button, would be more convenient if it's at the navigation section, bellow _account_ options
![Layout Mockup (2)](https://user-images.githubusercontent.com/53229085/63040110-5c035f80-be8a-11e9-8c1a-75543b3c7370.png)

**Comment by pablorich** [comment]
Yeah, that's where I was thinking it should go.
I am thinking about the stuff on the menu, I think we should put "Store" as a menu block and it can have categories as children as well as an "all" button to view all products. By doing that, then we might rename "Navigation" or straight up put the cart under "My account".
Don't take my word for this, let's talk it with the team to decide how we want it.

**Comment by alf-null** [comment]
Take a look to this please  :) 

![Layout Mockup (3)](https://user-images.githubusercontent.com/53229085/63300257-60ba8000-c29d-11e9-80d2-3ad6cf1016e6.png)

**Comment by Spawbreaker** [comment]
- We changed the layout on small desktop and desktop in the layout today. 
- There are some typos of "Product" as "Produc" in the first few mobile pages 

Otherwise, the content is great now. Nothing else to change here.

**Comment by alf-null** [comment]
Here is the latest layout adopted for the cart, think I fix all the typos. Hope everything is as expected.

![Layout Mockup (4)](https://user-images.githubusercontent.com/53229085/63370653-48ec0600-c348-11e9-8014-47cf919718b2.png)

**Comment by Spawbreaker** [comment]
Everything seems alright! Thanks Alfredo!
