### ISSUE TITLE
Mockup: Layout

### ISSUE THREAD

**Issue by pablorich** [IntersysConsulting/mdc_team_b_front#14]
As we've been working on the mockups we found that the layout needs improvement.

**Comment by Spawbreaker** [comment]
I contacted our product owner to see if he's content with this layout

![Layout Mockup](https://user-images.githubusercontent.com/37517471/63176518-af50eb80-c00b-11e9-8078-1b0dd2dbd303.png)

Still awaiting on his feedback

**Comment by Spawbreaker** [comment]
Updated layout with a minor addon: Modals

Design was approved by Product Owner.

![Staff Mockup (1)](https://user-images.githubusercontent.com/37517471/63196690-76306f80-c03b-11e9-94c1-a82534a173fa.png)

**Comment by Spawbreaker** [comment]
Final review of layout
- Changed medium screen menu distribuition
- Admin views now don't include customer views

![Staff Mockup](https://user-images.githubusercontent.com/37517471/63288662-e2e97b00-c282-11e9-9ca9-1a95b5ee3650.png)

**Comment by Spawbreaker** [comment]
Minor update 
- Changed small desktop font size and added padding to the menu
![Layout Mockup (1)](https://user-images.githubusercontent.com/37517471/63291215-bb95ac80-c288-11e9-80a9-443cd17a6434.png)

**Comment by pablorich** [comment]
as mentioned by @AnaSandoval-Intersys in #2 we don't need the billing, shipping, etc. options in the guest menu, it used to be okay when it was only 'my account' so that it would redirect the guest to the login page, but now we should just put a login button there

**Comment by Spawbreaker** [comment]
I agree that we may not need them but they can also redirect to sign up. Personally I think there's no harm in keeping them, but I would like to review it with the product owner.
