### ISSUE TITLE
Mockup: Banner Management

### ISSUE THREAD

**Issue by Spawbreaker** [IntersysConsulting/mdc_team_b_front#18]
- [x] Design
- [ ] Approval

- [x] As an admin I want to be able to upload new banners so that they can be stored in the database to be shown in the storefront.
- [x] As an admin I want to be able to select which banners I want to display on the storefront so that I can manage my website's advertisements. 
- [x] As an admin I want to be able to delete banners so that they are no longer stored in the database in case I don't want to use them again.

**Comment by roberbnd** [comment]
![Layout Mockup](https://user-images.githubusercontent.com/4907027/63894685-de277400-c9b2-11e9-9fba-ecef02fc1be2.png)

**Comment by roberbnd** [comment]
![Layout Mockup(1)](https://user-images.githubusercontent.com/4907027/63959462-d4a11900-ca51-11e9-830f-80f815b105ac.png)

**Comment by roberbnd** [comment]
![Layout Mockup(2)](https://user-images.githubusercontent.com/4907027/63960222-99074e80-ca53-11e9-995a-76f306e0adce.png)

**Comment by roberbnd** [comment]
I watched "My Cart"
![Layout Mockup(3)](https://user-images.githubusercontent.com/4907027/63960953-429b0f80-ca55-11e9-9397-faddcda0e509.png)

**Comment by AnaSandoval-Intersys** [comment]
Closing this issue after new versions of the mockups were approved at the sprint demo
