### ISSUE TITLE
Mockup: Billing Info

### ISSUE THREAD

**Issue by Spawbreaker** [IntersysConsulting/mdc_team_b_front#19]
- [x] As a customer I want to be able to see my billing information
- [x] As a customer I want to be able to add new billing information to my account
- [x] As a customer I want to be able to delete my billing information
- [x] As a customer I want to be able to edit my billing information

**Comment by Spawbreaker** [comment]
![Layout Mockup (8)](https://user-images.githubusercontent.com/37517471/63297809-dcb1c980-c297-11e9-82a3-5cef227ed887.png)

**Comment by pablorich** [comment]
Looks good

**Comment by AnaSandoval-Intersys** [comment]
I'm closing issue now, all modifications that should be made according to the feedback given by the product owner will be open as a new issue for clarity of this sprint.
