### ISSUE TITLE
Mockup: Storefront

### ISSUE THREAD

**Issue by Spawbreaker** [IntersysConsulting/mdc_team_b_front#2]
- [x] Design
- [ ] Approval

**Comment by Spawbreaker** [comment]
First version of the storefront mockup.

![Layout Mockup](https://user-images.githubusercontent.com/37517471/62895099-c5ad2d80-bd13-11e9-8102-c200156bc11c.png)

**Comment by Spawbreaker** [comment]
Fixed unnecessary Login buttons on small desktop. 
![Layout Mockup (3)](https://user-images.githubusercontent.com/37517471/62895579-cc887000-bd14-11e9-8ba8-c8ff28ed8366.png)

**Comment by pablorich** [comment]
Looks nice, here are some details:
menu on full size view should be higher.
On guest view I would change "My account" under Account bar to "Login" and "sign up", even if we have a button for that on the main page

**Comment by pablorich** [comment]
Maybe we can delete the search item button in the menu since we have a searchbar in the main view

**Comment by Spawbreaker** [comment]
Most websites nowadays obscure their log-out buttons as much as possible, I planned on it being inside the Account settings because of it. Adding it would require opening an issue on layout as it's not a storefront issue.
Will change the menu in a bit. 
The "My account" on guest was based off from Amazon, where they keep the same text even if it redirects to Log in-Sign up, but can change if you confirm you want it like that.

**Comment by Spawbreaker** [comment]
Updated Storefront with revisits to the layout
- Added filter button with functionality
- Search bar + Filter should be static and not scroll with the screen.

![Staff Mockup (1)](https://user-images.githubusercontent.com/37517471/63290438-0b737400-c287-11e9-963b-cffd47046f00.png)

**Comment by Spawbreaker** [comment]
Minor update
- Replaced small desktop menus
![Layout Mockup (2)](https://user-images.githubusercontent.com/37517471/63291310-eaac1e00-c288-11e9-83e2-7d3289fcb83a.png)

**Comment by AnaSandoval-Intersys** [comment]
Should the guest have the "Account" section in the layout since they don't actually have an account and we're not keeping their billing, delivery or orders? I think for guests we'd only have the Navigation section

**Comment by pablorich** [comment]
Wouldn't we need 'apply filter' buttons, or do you plan to apply the filter automatically when the user clicks an option?

**Comment by Spawbreaker** [comment]
> Should the guest have the "Account" section in the layout since they don't actually have an account and we're not keeping their billing, delivery or orders? I think for guests we'd only have the Navigation section

Commented on layout

- Added sorting
![Layout Mockup (14)](https://user-images.githubusercontent.com/37517471/63368326-4a66ff80-c343-11e9-988d-6e7d7d643548.png)
