### ISSUE TITLE
Mockup: Shipping info

### ISSUE THREAD

**Issue by Spawbreaker** [IntersysConsulting/mdc_team_b_front#20]
- [x] As a customer I want to be able to see my shipping information
- [x] As a customer I want to be able to add new shipping information to my account
- [x] As a customer I want to be able to delete my shipping information
- [x] As a customer I want to be able to edit my shipping information

**Comment by Spawbreaker** [comment]
![Layout Mockup (7)](https://user-images.githubusercontent.com/37517471/63297787-cefc4400-c297-11e9-9356-0270b8a5d981.png)

**Comment by pablorich** [comment]
This looks done to me

**Comment by AnaSandoval-Intersys** [comment]
I'm closing issue now, all modifications that should be made according to the feedback given by the product owner will be open as a new issue for clarity of this sprint.
