### ISSUE TITLE
Mockup: My Orders

### ISSUE THREAD

**Issue by Spawbreaker** [IntersysConsulting/mdc_team_b_front#21]
- [x]  As a customer I want to be able to review my past orders

**Comment by Spawbreaker** [comment]
![index](https://user-images.githubusercontent.com/37517471/63299287-0b7d6f00-c29b-11e9-9f8e-bc28b7e4d0a5.png)

**Comment by Spawbreaker** [comment]
![Layout Mockup (10)](https://user-images.githubusercontent.com/37517471/63299671-f2c18900-c29b-11e9-87da-f429a7971eef.png)

**Comment by pablorich** [comment]
Maybe less details and show all the details on a modal when clicked

**Comment by AnaSandoval-Intersys** [comment]
I'm closing issue now, all modifications that should be made according to the feedback given by the product owner will be open as a new issue for clarity of this sprint.
