### ISSUE TITLE
Mockup: Terms of Service

### ISSUE THREAD

**Issue by Spawbreaker** [IntersysConsulting/mdc_team_b_front#22]
- [x]  As a user I want to be able to see the terms of service of the application

**Comment by CrhistianH** [comment]
![Layout Mockup](https://user-images.githubusercontent.com/30354352/63368131-e5130e80-c342-11e9-9977-b47ef03cc1d7.jpg)

**Comment by CrhistianH** [comment]
![Layout Mockup](https://user-images.githubusercontent.com/30354352/63368587-d1b47300-c343-11e9-9b71-16e77bd0899c.png)

**Comment by AnaSandoval-Intersys** [comment]
I'm closing issue now, all modifications that should be made according to the feedback given by the product owner will be open as a new issue for clarity of this sprint.
