### ISSUE TITLE
Mockup: Help

### ISSUE THREAD

**Issue by Spawbreaker** [IntersysConsulting/mdc_team_b_front#23]
- [ ] As a user I want to be able to see a Frequently Asked Questions page
- [ ] As a user I want to be able to contact an admin for help

**Comment by Spawbreaker** [comment]
Help could be either a FAQ section or a Contact section. We should ask our PO which one before working on it... or doing both.

**Comment by pablorich** [comment]
Help as a "contact us" page

![Layout Mockup (1)](https://user-images.githubusercontent.com/15503226/64183740-f9b9d100-ce2f-11e9-89e1-c50a1b79d5d2.png)

**Comment by AnaSandoval-Intersys** [comment]
Closing this issue after new versions of the mockups were approved at the sprint demo
