### ISSUE TITLE
Mockup: Privacy Policy

### ISSUE THREAD

**Issue by Spawbreaker** [IntersysConsulting/mdc_team_b_front#24]
- [x] As a user I want to be able to see eCommerce's privacy policy.

**Comment by CrhistianH** [comment]
![Layout Mockup](https://user-images.githubusercontent.com/30354352/63368134-e6dcd200-c342-11e9-98fc-6e81ab7d004d.png)

**Comment by CrhistianH** [comment]
![Layout Mockup](https://user-images.githubusercontent.com/30354352/63368596-d547fa00-c343-11e9-97df-dc128f9ef2a8.jpg)

**Comment by AnaSandoval-Intersys** [comment]
I'm closing issue now, all modifications that should be made according to the feedback given by the product owner will be open as a new issue for clarity of this sprint.
