### ISSUE TITLE
Fix details from layout

### ISSUE THREAD

**Issue by AnaSandoval-Intersys** [IntersysConsulting/mdc_team_b_front#25]
- [x] Remove "Account" section for guests
- [x] For small desktop, change menu to be collapsible & on the side
- [x] Add number in cart icon, representing number of items in cart (make sure it matches with num. of items showed in cart mockup)

**Comment by Spawbreaker** [comment]
![image](https://user-images.githubusercontent.com/37517471/63893070-d1a11c80-c9ae-11e9-93f4-d07c88a1c01e.png)

What about this?

**Comment by Spawbreaker** [comment]
I made some changes because I did not like the design 
![image](https://user-images.githubusercontent.com/37517471/63950416-8edc5480-ca41-11e9-91ec-0d49f1e7bf43.png) (Hand drawn by me :D)

**Comment by AnaSandoval-Intersys** [comment]
Last design looks good to me!
I'd say this is ready to be closed. Same as with other issues, I will give it some time so others can leave feedback if they want to.
