### ISSUE TITLE
Fix details from mockups

### ISSUE THREAD

**Issue by AnaSandoval-Intersys** [IntersysConsulting/mdc_team_b_front#26]
- Add a "Remove filters" option in:
     - [x] Order management
     - [x] Product management 
     - [x] Storefront
	
- Under My Orders:
     - [x] Add information of payment provider for each order
     - [x] Make each order collapsible

-  Under My Account:
     - [ ] Add "My Cards" section
     - [x] Better distribute sections, make buttons text more understandable.

- Remove layout from:
     - [x] Sign up
     - [x] Log in Customer
     - [x] Log in Admin

- Others:
     - [ ] Add  _Add a new card_ option in checkout 
     - [x] Add _I Agree to T & C_ Checkbox in Sign up
     - [x] Remove "Password" fields in "Create admin account" (Admin management mockup)
     - [x] Add checkbox to make product digital in Product Management (add and edit)

**Comment by roberbnd** [comment]
some checkbooks is missing because like team we need to review the new design with the colors and it seems we going to discard "My cards" also we need an agreement

**Comment by AnaSandoval-Intersys** [comment]
Closing this issue after new versions of the mockups were approved at the sprint demo
