### ISSUE TITLE
Mockup: Register Card

### ISSUE THREAD

**Issue by AnaSandoval-Intersys** [IntersysConsulting/mdc_team_b_front#27]
- [ ] As an user, I want to be able to add a new card to my payment methods

**Comment by pablorich** [comment]
Credit Card Mockup. Might be updated to new design or get discarded.
![Layout Mockup](https://user-images.githubusercontent.com/15503226/64124194-f6f5a800-cd6b-11e9-9949-c51a496b8f6a.png)
