### ISSUE TITLE
Add color to mockup: Layout

### ISSUE THREAD

**Issue by AnaSandoval-Intersys** [IntersysConsulting/mdc_team_b_front#29]
- [x] As the product owner, I want to see the design for the layout of my page, now including the color palette provided,

**Comment by Spawbreaker** [comment]
Preview of color and fixes for general design approval before applying color to the rest of the layout. 
Still missing a menu indicator for mobile. Also including a second option for color to discuss. 


- Defined a theme in Figma for easy access to customer's brand colors. 
- White isn't final

![Layout Mockup (18)](https://user-images.githubusercontent.com/37517471/63550965-775d1300-c4f9-11e9-92f4-ef13560e7a92.png)
![Small Desktop_ Hidden Menu (1)](https://user-images.githubusercontent.com/37517471/63552118-7679b080-c4fc-11e9-8be2-ff3ede808932.png)

**Comment by Spawbreaker** [comment]
![image](https://user-images.githubusercontent.com/37517471/63950560-d7940d80-ca41-11e9-9166-f3148408c7b7.png)

We have a very limited palette, considering the second shade ( #555555 ) we have only two shades of gray. Using white could be an option. For some modals we may be able to use the teal one ( #09c1b0 ). But let me make a second set with the second shade of the light blue ( #6caae4 )

**Comment by Spawbreaker** [comment]
For modal variety I would propose making a bunch of css classes based on bootstrap to be able to use any of our colors like this: 
![image](https://user-images.githubusercontent.com/37517471/63951517-8127ce80-ca43-11e9-9614-ecce4053469c.png)

It gives us versatility to use every color in the palette and breaks from the heavy blue design.

**Comment by AnaSandoval-Intersys** [comment]
That idea seems good to me! We can leave it in the layout mockup to represent the possibility so it doesn't affect the mockups that are already finished. 
For me this issue is ready to be closed. I'll leave it open a few hours in case somebody else has any other feedback
