### ISSUE TITLE
Mockup: Admin Login

### ISSUE THREAD

**Issue by Spawbreaker** [IntersysConsulting/mdc_team_b_front#3]
- [x] Design
- [x] Approval

**Comment by christianahvilla** [comment]
This is a draft 

[Mockup](https://www.figma.com/file/pWPBcURDWrc6EeYflw7Euq/Admin-Login)

![Admin Login](https://user-images.githubusercontent.com/28796557/62808126-d152e700-babc-11e9-9216-fadc72416914.jpg)

**Comment by Spawbreaker** [comment]
Hey Christian!

I love the minimalistic design, specially in an administrative log in, but I believe we shouldn't expose an admin sign up. Admin sign ups should be handled in the Staff site under admin priviledges.

Looking forward to it being on the new layout!

**Comment by christianahvilla** [comment]
> Hey Christian!
> 
> I love the minimalistic design, specially in an administrative log in, but I believe we shouldn't expose an admin sign up. Admin sign ups should be handled in the Staff site under admin priviledges.
> 
> Looking forward to it being on the new layout!

I got it, now I updated the design, please me if you have another comment

**Comment by Spawbreaker** [comment]
Updated with new layout. 

![Staff Mockup (5)](https://user-images.githubusercontent.com/37517471/63200276-40dd4f00-c046-11e9-8214-67e78b690840.png)

**Comment by Spawbreaker** [comment]
- Updated Layout
![Layout Mockup (12)](https://user-images.githubusercontent.com/37517471/63302129-f952ff00-c2a1-11e9-82d0-091918232411.png)

**Comment by Spawbreaker** [comment]
- [ ] Ask product owner about admin log in menu content
