### ISSUE TITLE
Add color to mockups: Admin Views

### ISSUE THREAD

**Issue by AnaSandoval-Intersys** [IntersysConsulting/mdc_team_b_front#30]
- [x] Order Management
- [x] Product Management
- [x] Staff
- [x] Terms of Service
- [x] Privacy Policy
- [x] Banner Management

**Comment by CrhistianH** [comment]
Terms of service:
![Layout Mockup (2)](https://user-images.githubusercontent.com/30354352/63893812-b7683e00-c9b0-11e9-90f1-3009a29323c5.jpg)

**Comment by CrhistianH** [comment]
Privacy Policy: 
![Layout Mockup (3)](https://user-images.githubusercontent.com/30354352/63893830-c51dc380-c9b0-11e9-92d4-0c62f80061db.jpg)

**Comment by CrhistianH** [comment]
I cannot work on the Banner Management site since it did not exist a while ago. I think it is now under development by another teammate. I'll wait for it to be done so I can add color to it.

**Comment by CrhistianH** [comment]
Banner management mockup was already colored too. I think all the mockups on this Issue are already covered.

**Comment by Spawbreaker** [comment]
TOS and Privacy Policy could use a title to differentiate them. 

I have **never** seen them in a not white background + black font, maybe there's a legislation for it? I would do a little bit of research about those two.

**Comment by AnaSandoval-Intersys** [comment]
I have an issue with aligning to the left instead of justifying in long text, especially if it's "serious information" like this. I'd also suggest adding the titles AND justifying the text alignment.

**Comment by CrhistianH** [comment]
![Layout Mockup (4)](https://user-images.githubusercontent.com/30354352/63976867-edbcc080-ca77-11e9-9d8f-93a13c749c34.jpg)

**Comment by CrhistianH** [comment]
![Layout Mockup (5)](https://user-images.githubusercontent.com/30354352/63976880-f57c6500-ca77-11e9-87f3-338c2e3cd86d.jpg)

**Comment by AnaSandoval-Intersys** [comment]
Good! I just changed the color for the titles to match the color palette given, and I'd say now it's ready to close. Thanks!
