### ISSUE TITLE
Add color: Checkout

### ISSUE THREAD

**Issue by AnaSandoval-Intersys** [IntersysConsulting/mdc_team_b_front#34]
- [x] Copy approved layout to Checkout
- [x] Add color to components of Checkout mockup

**Comment by Spawbreaker** [comment]
The insert addresses is a repeated view from #35 ( My Billing / My Shipping ) and should just use that instead (No need to copy it over) but instead it should be a "Select address" that displays all of the user's addresses + the possibility of "Use X address as Y address too". 

I made some small color changes to stay on palette. 

Still needs to implement the consideration of asking a guest for their email during their checkout and a "Your order has been processed" screen.

**Comment by Spawbreaker** [comment]
Majorly reworked this with new information
![Layout Mockup (5)](https://user-images.githubusercontent.com/37517471/63979081-a802f680-ca7d-11e9-8e78-293b8e4b2fbd.jpg)

**Comment by AnaSandoval-Intersys** [comment]
Closing this issue after new versions of the mockups were approved at the sprint demo
