### ISSUE TITLE
Add color: shipping and billing info

### ISSUE THREAD

**Issue by AnaSandoval-Intersys** [IntersysConsulting/mdc_team_b_front#35]
- [x] Copy approved layout to shipping info
- [x] Copy approved layout to billing info
- [x] Add color to components of shipping mockup
- [x] Add color to  components of billing mockup

**Comment by roberbnd** [comment]
Do you like?
![Layout Mockup](https://user-images.githubusercontent.com/4907027/63893466-d74b3200-c9af-11e9-9672-bf73c84f3ad6.png)

**Comment by Spawbreaker** [comment]
I would change "Default" to Preferred for our customer. 
Also change the title, both say Shipping. 

Consider the schema of these two objects to see what data should be requested of them. 
We can't use 000000 black, please use our palette colors, button text usually look better in white with the dark blue. 


![image](https://user-images.githubusercontent.com/37517471/63895644-4a0adc00-c9b5-11e9-8078-c6c1307855eb.png)

**Comment by pablorich** [comment]
Add and edit pages look the same, I would change the button on the edit page to "save" and maybe put placeholder info in the fields

**Comment by AnaSandoval-Intersys** [comment]
Closing this issue after new versions of the mockups were approved at the sprint demo
