### ISSUE TITLE
Add color: My orders

### ISSUE THREAD

**Issue by AnaSandoval-Intersys** [IntersysConsulting/mdc_team_b_front#36]
- [x] Copy approved layout to My Orders
- [x] Add color to components of My Orders mockup

**Comment by roberbnd** [comment]
![Layout Mockup(4)](https://user-images.githubusercontent.com/4907027/63962413-71ff4b80-ca58-11e9-9f7a-01a1e2b29192.png)

**Comment by roberbnd** [comment]
![Layout Mockup(4)](https://user-images.githubusercontent.com/4907027/63962920-724c1680-ca59-11e9-8ba1-5ae7781bdcbd.png)

**Comment by AnaSandoval-Intersys** [comment]
Closing this issue after new versions of the mockups were approved at the sprint demo
