### ISSUE TITLE
Mockup: Product Management

### ISSUE THREAD

**Issue by Spawbreaker** [IntersysConsulting/mdc_team_b_front#4]
- [x] Design
- [ ] Approval

**Comment by CrhistianH** [comment]
This one is huge, so please see the original mockup at Figma if necessary to see the full details of it.

![image](https://user-images.githubusercontent.com/30354352/63056983-d6de7180-beae-11e9-9e5d-ee6077b574c3.png)

**Comment by pablorich** [comment]
In terms of functionality I think we only need to add a stock field.
In terms of design, I like the main idea but there's a lot of stuff that can be improved, maybe we can chat about the things that I think look odd.

**Comment by CrhistianH** [comment]
Adjusted to meet today's new requirements. Hopefully this will be the final review.

![Product management Mockup V1 2](https://user-images.githubusercontent.com/30354352/63299879-74191b80-c29c-11e9-8e00-f0de4a3e8399.jpg)

**Comment by Spawbreaker** [comment]
I like this, but maybe it would be wise to approach our product owner about stock, at least to consider the space for it in the design... this could also modify storefront. I'll try to get in touch with him about it and add onto it in a while.

**Comment by Spawbreaker** [comment]
Product owner is alright with moving changes to this to the next sprint, so let's close this down for the sprint so we can focus our efforts into other pressing matters! Great Job Edwin, thanks.
