### ISSUE TITLE
React component: Search

### ISSUE THREAD

**Issue by alf-null** [IntersysConsulting/mdc_team_b_front#45]
Create the Search generic component for all three views.

![Capture](https://user-images.githubusercontent.com/53873395/64456102-06029000-d0b5-11e9-8c78-485f29237762.PNG)

**Comment by pablorich** [comment]
![image](https://user-images.githubusercontent.com/15503226/66873541-4d125980-ef6e-11e9-8694-ab7fce669122.png)
![image](https://user-images.githubusercontent.com/15503226/66873582-5bf90c00-ef6e-11e9-86b5-0e8dba6a66cb.png)
![image](https://user-images.githubusercontent.com/15503226/66873593-65827400-ef6e-11e9-9b3d-eae453c57d80.png)
