### ISSUE TITLE
React component: Textbox

### ISSUE THREAD

**Issue by alf-null** [IntersysConsulting/mdc_team_b_front#49]
Create the Textbox generic component for all three views.

![image](https://user-images.githubusercontent.com/37517471/64819797-b3bde500-d574-11e9-88fd-d8f9ab712a50.png)
![image](https://user-images.githubusercontent.com/37517471/64819819-bfa9a700-d574-11e9-8ed9-7c1389300b4a.png)
![image](https://user-images.githubusercontent.com/37517471/64819835-c7694b80-d574-11e9-9860-1f3c1e4e7c2a.png)

**Comment by Spawbreaker** [comment]
This is unecessary, just import from React-bootstrap when needed
