### ISSUE TITLE
Mockup: Checkout

### ISSUE THREAD

**Issue by Spawbreaker** [IntersysConsulting/mdc_team_b_front#5]
- [ ] Design
- [ ] Approval

**Comment by roberbnd** [comment]
![che](https://user-images.githubusercontent.com/4907027/62965289-4fb7cd80-bdca-11e9-806e-e3b225d86541.jpg)

**Comment by pablorich** [comment]
You can delete Home's description from billing info since we only require the address to verify it corresponds to the credit card.
Try to add more detail on the resume and payment views.
Think of the order in which the screens will be displayed, try to take inspiration on other websites.
Take your time making the other views and refining the mockup.

**Comment by roberbnd** [comment]
![Staff Mockup](https://user-images.githubusercontent.com/4907027/63130712-02ca2780-bf81-11e9-8072-221f7edab107.jpg)

**Comment by Spawbreaker** [comment]
Hey Robert!

Making the "select a payment provider" radial button options smaller would make more sense. [They are usually the size of the font used.](https://www.keynotesupport.com/websites/contact-form-example-radio-buttons.shtml)

In the full desktop view **I** would consider putting the shipping and delivery info, and summary and payment provider on top of eachother (Feel free to extend the view vertically to fit them both.) instead of side by side, but if you feel this fits the app better then there's no need to change it, as I have seen other stores use either of the formats. 

After changing the radial buttons size I would consider this one done, great improvement friend!

**Comment by roberbnd** [comment]
![nuevo](https://user-images.githubusercontent.com/4907027/63203735-18118580-c057-11e9-85b4-d3aecdaf2b7f.jpg)

**Comment by roberbnd** [comment]
![Staff Mockup](https://user-images.githubusercontent.com/4907027/63283992-3f936880-c278-11e9-9c7c-ffdf807655b8.jpg)

**Comment by roberbnd** [comment]
![Uploading Layout Mockup.jpg…]()

**Comment by roberbnd** [comment]
![Layout Mockup](https://user-images.githubusercontent.com/4907027/63349427-06630300-c321-11e9-92e6-e590ccfd3a80.jpg)

**Comment by Spawbreaker** [comment]
I think this is great! Thanks for your hard work Robert! I'll close this issue now.

**Comment by Spawbreaker** [comment]
- Minor update: Added title.
![Layout Mockup](https://user-images.githubusercontent.com/37517471/63381541-82c80700-c35e-11e9-9d0f-41966dc585b0.jpg)
