### ISSUE TITLE
React component: Links

### ISSUE THREAD

**Issue by alf-null** [IntersysConsulting/mdc_team_b_front#50]
Create the Links generic component for all three views.

![image](https://user-images.githubusercontent.com/37517471/64819545-1662b100-d574-11e9-9567-8b063904aafa.png)
![image](https://user-images.githubusercontent.com/37517471/64819573-24183680-d574-11e9-9256-61f29866d445.png)
![image](https://user-images.githubusercontent.com/37517471/64819593-2c707180-d574-11e9-8135-a757d09d79d0.png)
![image](https://user-images.githubusercontent.com/37517471/64819608-34301600-d574-11e9-8848-f2a094b7f966.png)

**Comment by AnaSandoval-Intersys** [comment]
No need to make a component for links.
