### ISSUE TITLE
React component: Scroll View

### ISSUE THREAD

**Issue by alf-null** [IntersysConsulting/mdc_team_b_front#57]
Create the Scroll View generic component for all three views.

![image](https://user-images.githubusercontent.com/53229085/64398130-5a602e00-d029-11e9-9ab2-67a9d4b9a77f.png)

**Comment by pablorich** [comment]
![image](https://user-images.githubusercontent.com/15503226/66873400-f7d64800-ef6d-11e9-8c83-e1a4490e87a8.png)
![image](https://user-images.githubusercontent.com/15503226/66873412-fefd5600-ef6d-11e9-92a2-bda1bb2a9a22.png)
![image](https://user-images.githubusercontent.com/15503226/66873448-14728000-ef6e-11e9-8dff-5a4c27b78868.png)
Only chrome supports scroll styling
