### ISSUE TITLE
Mockup: Sign up

### ISSUE THREAD

**Issue by Spawbreaker** [IntersysConsulting/mdc_team_b_front#6]
- [x] Design
- [x] Approval

**Comment by christianahvilla** [comment]
[Mockup](https://www.figma.com/file/p2dw9MIraxuHWiWKHK8spO/Login?node-id=0%3A1)

![Login](https://user-images.githubusercontent.com/28796557/62901120-9b626c80-bd21-11e9-89ff-1f227e236a2d.jpg)

**Comment by pablorich** [comment]
We need to capture more details to create an account.

**Comment by christianahvilla** [comment]
[Mockup](https://www.figma.com/file/p2dw9MIraxuHWiWKHK8spO/Sign-up?node-id=0%3A1)

![Sign up](https://user-images.githubusercontent.com/28796557/62953665-87674b00-bdb3-11e9-87d2-3e6ea48c1b71.jpg)

**Comment by Spawbreaker** [comment]
Updated with new layout. 

![Staff Mockup (7)](https://user-images.githubusercontent.com/37517471/63200466-f9a38e00-c046-11e9-9173-b45916da21f0.png)

**Comment by Spawbreaker** [comment]
- Updated Layout
![Layout Mockup (13)](https://user-images.githubusercontent.com/37517471/63302146-04a62a80-c2a2-11e9-8b24-6f141dc0b8e9.png)
