### ISSUE TITLE
React component: Price

### ISSUE THREAD

**Issue by alf-null** [IntersysConsulting/mdc_team_b_front#65]
Create the Price generic component for all three views.

![image](https://user-images.githubusercontent.com/53229085/64452993-2cbcc880-d0ad-11e9-8ce5-7083b4015465.png)

**Comment by pablorich** [comment]
![image](https://user-images.githubusercontent.com/15503226/64710894-5cd5e400-d47e-11e9-82d3-37bbcb641b32.png)
![image](https://user-images.githubusercontent.com/15503226/64710909-63fcf200-d47e-11e9-9b40-1bda49b2a373.png)
Will integrate into project after mergin Ricardo's buttons
