### ISSUE TITLE
Mockup: Customer Login

### ISSUE THREAD

**Issue by Spawbreaker** [IntersysConsulting/mdc_team_b_front#7]
- [x] Design
- [x] Approval

**Comment by christianahvilla** [comment]
[Mockup](https://www.figma.com/file/sp4FX76kG6jc4Qwlfi2pid/Customer-Login?node-id=0%3A1)

![Customer Login](https://user-images.githubusercontent.com/28796557/62901901-969eb800-bd23-11e9-8db4-66351586785f.jpg)

**Comment by Spawbreaker** [comment]
Updated this mock up to the new Layout, keeping Christian's design. 

![Staff Mockup (4)](https://user-images.githubusercontent.com/37517471/63200125-b4cb2780-c045-11e9-8125-fe141a1f5d03.png)

**Comment by Spawbreaker** [comment]
- Updated Layout
![Layout Mockup (11)](https://user-images.githubusercontent.com/37517471/63302099-e3ddd500-c2a1-11e9-91f7-4bfa09fe8ae9.png)
