### ISSUE TITLE
React component: Last order card

### ISSUE THREAD

**Issue by alf-null** [IntersysConsulting/mdc_team_b_front#70]
Create the Last order generic component for all three views.

![image](https://user-images.githubusercontent.com/53229085/64451835-a7d0af80-d0aa-11e9-823a-91a0c0159a54.png)

**Comment by Spawbreaker** [comment]
![image](https://user-images.githubusercontent.com/37517471/64877432-0a7bfb00-d617-11e9-80be-bdd9102f705b.png)
 Button was changed to orange after confering with the team
