### ISSUE TITLE
React component: Alert

### ISSUE THREAD

**Issue by alf-null** [IntersysConsulting/mdc_team_b_front#76]
Create the Alert generic component for all three views.

![image](https://user-images.githubusercontent.com/53229085/64449522-ba94b580-d0a5-11e9-8e7b-79732af5649a.png)

![image](https://user-images.githubusercontent.com/53229085/64449550-cd0eef00-d0a5-11e9-9814-7d5b4bc2e536.png)

![image](https://user-images.githubusercontent.com/53229085/64449565-d26c3980-d0a5-11e9-81c6-0e0b1846c5b0.png)

**Comment by CrhistianH** [comment]
This has been already implemented. Component is ready.
