### ISSUE TITLE
React component: Checkout table

### ISSUE THREAD

**Issue by alf-null** [IntersysConsulting/mdc_team_b_front#77]
Create the Row container generic component for all three views.

![image](https://user-images.githubusercontent.com/53229085/64449454-9042f800-d0a5-11e9-800e-6d303dd287e2.png)

**Comment by Spawbreaker** [comment]
Updated to match this
![image](https://user-images.githubusercontent.com/37517471/65062684-27c80680-d942-11e9-802d-0e4efa8995ab.png)
