### ISSUE TITLE
Mockup: Staff

### ISSUE THREAD

**Issue by Spawbreaker** [IntersysConsulting/mdc_team_b_front#8]
- [x] Design
- [x] Approval

**Comment by AnaSandoval-Intersys** [comment]
Here goes the Mockup for staff (or admin management):

![Staff Mockup](https://user-images.githubusercontent.com/53873395/63039948-fe6f1300-be89-11e9-9432-a33d7bd59c0e.png)

¿Comments?

**Comment by pablorich** [comment]
- Maybe place the _Add admin_ button on the top for the 3 view sizes, also I think it's better to use the same style of button for the 3 sizes

- On small view for modifying admin the text is wrong

I don't know if I'm missing info but I thought we were able to demote the admin access from this menu

**Comment by AnaSandoval-Intersys** [comment]
Thanks, here's the new version.

![Staff Mockup](https://user-images.githubusercontent.com/53873395/63042977-d2a35b80-be90-11e9-84e5-e42e81f8130b.png)

Since we were told all admins have the same access level, I see no point in demoting admins (admin to customer makes no real sense to me, and it's not requested for any of the versions)

**Comment by Spawbreaker** [comment]
I hadn't had time to check this one myself, I would've also suggested moving the Add button to the top  since it would be very annoying to scroll all the way down to add a new admin. 
We don't have any requirements that say that one may change a user's permissions, so I think that's alright. 

I like this, it's a great job!

**Comment by AnaSandoval-Intersys** [comment]
Added some small changes, especially to consider than an admin can only edit himself and for changing the password.

![Staff Mockup 2 0](https://user-images.githubusercontent.com/53873395/63291510-470f3d80-c289-11e9-8e3b-9ce0333ce73b.png)
