### ISSUE TITLE
React component: Product management item container

### ISSUE THREAD

**Issue by alf-null** [IntersysConsulting/mdc_team_b_front#83]
Create the Product management item container generic component for all three views.

![image](https://user-images.githubusercontent.com/53229085/64447423-f9743c80-d0a0-11e9-987d-667aea599e1c.png)

**Comment by Spawbreaker** [comment]
Use this class on the title/link/product name to limit the text to a certain sized box. 
https://gist.github.com/Spawbreaker/ba7a8f27615b3f5a099751c73811e7fe
