### ISSUE TITLE
React component: Text container (modal with title)

### ISSUE THREAD

**Issue by alf-null** [IntersysConsulting/mdc_team_b_front#86]
Create the Text container (modal with title) generic component for all three views.

![image](https://user-images.githubusercontent.com/53229085/64446001-5c63d480-d09d-11e9-90e0-b0c597eec9ba.png)

![image](https://user-images.githubusercontent.com/53229085/64446016-64bc0f80-d09d-11e9-940d-c79e070c61b9.png)

![image](https://user-images.githubusercontent.com/53229085/64446065-82897480-d09d-11e9-9415-44a84f06272a.png)

**Comment by alf-null** [comment]
![image](https://user-images.githubusercontent.com/53229085/64358587-59e57a00-cfcc-11e9-86f3-c0f2f05f2403.png)

![image](https://user-images.githubusercontent.com/53229085/64358613-67026900-cfcc-11e9-8fe9-865b8e94b2be.png)

![image](https://user-images.githubusercontent.com/53229085/64358754-a466f680-cfcc-11e9-8d59-6593834b908b.png)

**Comment by CrhistianH** [comment]
This component was created in the process of developing the Privacy Policy and Terms of Service "views". We all agreed to keep them as this kind of modal component.
Example of implementation on #121
