### ISSUE TITLE
Mockup: Order Management

### ISSUE THREAD

**Issue by Spawbreaker** [IntersysConsulting/mdc_team_b_front#9]
- [x] Design
- [x] Approval

**Comment by Spawbreaker** [comment]
This view is only accessible to admin users. If a guest or customer try to get access to it the front end should respond with a 403; as well as the back-end APIs.  Maybe I should add in another comment to clarify this? 
Order Items should be internally scrollable, without moving the rest of the UI. 
The button labeled as "Status" should display the Status name AND be color coded for easy access.

![Layout Mockup (4)](https://user-images.githubusercontent.com/37517471/62963396-8be92f00-bdc6-11e9-9aae-1e74f881542a.png)

Should I add in these as comments to the mockup?

**Comment by pablorich** [comment]
I don't think it's necessary, it's pretty common for this stuff to be color coded.
I think the menu items on the full size view should be higher.
Besides that, everything looks fine for me, maybe change the order of the buttons "change status" and "view items". Up to you, I'll give you some time if you want to change bits of the design

**Comment by pablorich** [comment]
Maybe we can delete the search item button in the menu since we have a searchbar in the main view.
Also we need a log out button.

**Comment by Spawbreaker** [comment]
Woops, again, search-item button in the menu is in layout. Should reopen the issue there if it´s a real problem. It's, again, based off from Amazon where the search item (category?) is accessible from anywhere in the menu.

I'm not sure with flipping Change status and View Items, but can do if you really want me to.

**Comment by Spawbreaker** [comment]
Hey! I changed the layout to the new one and added modal usage for the view.

Also rearranged the items

![Staff Mockup (2)](https://user-images.githubusercontent.com/37517471/63196580-336e9780-c03b-11e9-845a-2afff5fbeb25.png)

**Comment by Spawbreaker** [comment]
- Updated with new Layout 
- Added Change Status on View by clicking on the status button
- Added filter/search
![Layout Mockup (5)](https://user-images.githubusercontent.com/37517471/63296404-9b6bea80-c294-11e9-8af9-c0bc9e8a7b4c.png)

**Comment by AnaSandoval-Intersys** [comment]
- I think I'd be best to put the search bar above the filter options in the filter modal, users are kind of used to search bars being on top and unless it's locked in its position while the filter options are scrollable it wouldn't be practical to put it at the bottom

- I believe the alert for "Change status" confirmation needs padding at the sides.

Aside from those two things, it looks great!

**Comment by Spawbreaker** [comment]
- Changed search bar to top 
- Added padding to change status

Closing this issue now!
![Layout Mockup (15)](https://user-images.githubusercontent.com/37517471/63368701-0fb19700-c344-11e9-9115-3aea316ef510.png)
