### ISSUE TITLE
React Component: Navigation Button

### ISSUE THREAD

**Issue by Spawbreaker** [IntersysConsulting/mdc_team_b_front#92]
#43 Dependency: 

![image](https://user-images.githubusercontent.com/37517471/64722357-eba12b80-d493-11e9-9209-df07268b26f3.png)
There are more samples on the linked issue

**Comment by CrhistianH** [comment]
This issue is now solved after the layout was implemented. This navigation button component was done by @AnaSandoval-Intersys.
